"""add cv_versions table

Revision ID: 930e098ec341
Revises: d395c36ba4a0
Create Date: 2026-03-07 14:43:13.093142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930e098ec341'
down_revision: Union[str, Sequence[str], None] = 'd395c36ba4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_ad_text', sa.Text(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('cv_summary', sa.Text(), nullable=True),
    sa.Column('cv_skills', sa.Text(), nullable=True),
    sa.Column('cv_experience', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('missing_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_versions_id'), 'cv_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_versions_id'), table_name='cv_versions')
    op.drop_table('cv_versions')
    # ### end Alembic commands ###
