"""add monitor_runs

Revision ID: d91230a8c3c6
Revises: 05ad4f8ac94e
Create Date: 2026-02-21 20:00:47.197949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91230a8c3c6'
down_revision: Union[str, Sequence[str], None] = '05ad4f8ac94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_runs_checked_at'), 'monitor_runs', ['checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_runs_id'), 'monitor_runs', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_runs_monitor_id'), 'monitor_runs', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_runs_monitor_id'), table_name='monitor_runs')
    op.drop_index(op.f('ix_monitor_runs_id'), table_name='monitor_runs')
    op.drop_index(op.f('ix_monitor_runs_checked_at'), table_name='monitor_runs')
    op.drop_table('monitor_runs')
    # ### end Alembic commands ###
